# Generated by Django 4.0.5 on 2022-06-30 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceinfield',
            old_name='analyzer_id',
            new_name='analyzer',
        ),
        migrations.RenameField(
            model_name='deviceinfield',
            old_name='customers_id',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customers',
        ),
    ]
